# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# before:
# hooks:
# you may remove this if you don't use vgo
#   - go mod tidy
# you may remove this if you don't need go generate
#   - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - ids:
      - darwin
    github:
      owner: dnoberon
      name: homebrew-dnoberon
    commit_author:
      name: dnoberon
      email: johnw.darrington@gmail.com
    caveats: |
      Live the life of plain text contracting.
      We are glad you have joined us.
      Completions are coming shortly.
    homepage: https://monax.io
    description: &description |
      Welcome, dear marmot, to the revolution!

      This is a high level client to the Agreements Network
      it's written in Go by your furry friends at Monax.

      We use it to keep our plain text contracts in sync
      with our repositories that live on the Agreements
      Network via the Monax Platform API.

      Live the life of plain text contracting.
    dependencies: []
    conflicts: []
    plist: ""
    install: |
      bin.install "nax"
